<div id="content">
    <h2>Mes disques -> <?php echo $user ?> </h2>
    <a class='btn btn-primary add' href='Disques' >Créer un disque</a>
    <div class="panel panel-default">
        <div class="panel-body">

            <?php
                $i=0;
                foreach($noms as $nom) {
                    echo '<span class="glyphicon glyphicon-hdd"></span>' . ' ';
                    echo $nom . ' ';
                    echo $occupations[$nom] . "octets/" . $quotas[$nom] . $unites[$nom];
                    $nom = trim($nom);
                    echo $pgbs[$i];
                    echo '<a class=\'btn btn-primary add\' style="width: 100%" href=\'Scan/'. $ids[$nom] . '\' >Créer un disque</a> <br/><br/>';
                    $i+=1;
                }
            ?>
        </div>
    </div>
</div>